# Revision

In [ ]:
# DataFrame - Intro
# Creation of the DataFrame -
1. List
2. Another DataFrame
3. Dict
4. Series
5. Ndarray
# Columns - CRUD
Column Selection
Column Addition
Column Deletion - del, pop, drop

In [ ]:
import pandas as pd

In [ ]:
data = {"Apples":[102, 500, 250, 75],"Grapes":[50, 150, 90, 45]}
df = pd.DataFrame(data,index=["A", "B", "C", "D"])

In [ ]:
df

   Apples  Grapes
A     102      50
B     500     150
C     250      90
D      75      45

In [ ]:
df[['Grapes']]

   Grapes
0      50
1     150
2      90
3      45

In [ ]:
df['Bananas'] = df['Grapes'] + 50

In [ ]:
df['Pear'] = df['Bananas'] + 100
df['Mangoes'] = df['Pear'] + 500
df['Jackfruit'] = df['Grapes'] + 150
df['Strawberry'] = df['Jackfruit'] + 200
df['Oranges'] = df['Strawberry'] + 70

In [ ]:
df

   Apples  Grapes  Bananas
0     102      50      100
1     500     150      200
2     250      90      140
3      75      45       95

In [ ]:
df.drop(['Bananas'], axis=1, inplace=True)

In [ ]:
df

   Apples  Grapes
0     102      50
1     500     150
2     250      90
3      75      45

# Row - CRUD

In [ ]:
df

   Apples  Grapes  Bananas  Pear  Mangoes  Jackfruit  Strawberry  Oranges
A     102      50      100   200      700        200         400      470
B     500     150      200   300      800        300         500      570
C     250      90      140   240      740        240         440      510
D      75      45       95   195      695        195         395      465

* Row selection

In [ ]:
loc & iloc

In [ ]:
# loc -> Index_name
df.loc["A":"D"]

   Apples  Grapes  Bananas  Pear  Mangoes  Jackfruit  Strawberry  Oranges
A     102      50      100   200      700        200         400      470
B     500     150      200   300      800        300         500      570
C     250      90      140   240      740        240         440      510
D      75      45       95   195      695        195         395      465

In [ ]:
# iloc -> index
df.iloc[2:3]

   Apples  Grapes  Bananas  Pear  Mangoes  Jackfruit  Strawberry  Oranges
C     250      90      140   240      740        240         440      510

* Row Addition

In [ ]:
student_marks = {"Name":["Rahul", "Rohit", "Venkat", "Sahil", "Ankita"],
                 "OS":[25, 75.5, 96, 0, 100],
                 "DBMS":[20, 80, 60, 50, 99]}

df1 = pd.DataFrame(student_marks)

In [ ]:
df1

     Name     OS  DBMS
0   Rahul   25.0    20
1   Rohit   75.5    80
2  Venkat   96.0    60
3   Sahil    0.0    50
4  Ankita  100.0    99

In [ ]:
data2 = {"Name":"Robby", "OS":60.5, "DBMS":55.5}

In [ ]:
# 1st Method -> append()
df1 = df1.append(data2,ignore_index=True)

In [ ]:
df1

     Name     OS  DBMS
0   Rahul   25.0  20.0
1   Rohit   75.5  80.0
2  Venkat   96.0  60.0
3   Sahil    0.0  50.0
4  Ankita  100.0  99.0
5   Robby   60.5  55.5

In [ ]:
# 2nd Method -> concat()
data3 = {"Name":"Spiderman", "OS":90, "DBMS":100}
df3 = pd.DataFrame(data3,index=[0])

# arr.append(1)

In [ ]:
df3

    Name    OS  DBMS
0  Venom  80.5    75

In [ ]:
df1 = pd.concat([df1, df3])

In [ ]:
df1

        Name     OS   DBMS
0      Venom   80.5   75.0
1      Rahul   25.0   20.0
2      Rohit   75.5   80.0
3     Venkat   96.0   60.0
4      Sahil    0.0   50.0
5     Ankita  100.0   99.0
6      Robby   60.5   55.5
7      Venom   80.5   75.0
0      Venom   80.5   75.0
0  Spiderman   90.0  100.0

In [ ]:
df1.loc[[0]]

        Name    OS   DBMS
0      Venom  80.5   75.0
0      Venom  80.5   75.0
0  Spiderman  90.0  100.0

In [ ]:
df1

        Name     OS   DBMS
0      Venom   80.5   75.0
1      Rahul   25.0   20.0
2      Rohit   75.5   80.0
3     Venkat   96.0   60.0
4      Sahil    0.0   50.0
5     Ankita  100.0   99.0
6      Robby   60.5   55.5
7      Venom   80.5   75.0
0      Venom   80.5   75.0
0  Spiderman   90.0  100.0

In [ ]:
df1.loc[[4]]

    Name   OS  DBMS
4  Sahil  0.0  50.0

In [ ]:
df1.iloc[5] = ["Hulk", 60]

ValueError: ignored

In [ ]:
df1

       Name     OS   DBMS
0  Starlord   10.0    9.0
1     Rahul   25.0   20.0
2     Rohit   75.5   80.0
3    Venkat   96.0   60.0
4     Steve   67.0   23.0
5    Ankita  100.0   99.0
6     Robby   60.5   55.5
7     Venom   80.5   75.0
0    Vision  100.0  105.0
0    Vision  100.0  105.0

* Row Deletion

In [ ]:
del, pop, drop

In [ ]:
del df1.loc[[6]]

AttributeError: ignored

In [ ]:
df1.pop(df1.loc[[6]])

ValueError: ignored

In [ ]:
df1.loc.pop([6])

AttributeError: ignored

In [ ]:
df1.pop(6)

KeyError: ignored

In [ ]:
df1.drop(0, inplace=True)

In [ ]:
df1

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

In [ ]:
lis = [1,2,3,4,5,6,7]

* Data Exploration
* Data Cleaning
* Data Manipulation
* Data Analysis

In [ ]:
df1

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

# Data Exploration

In [ ]:
df

   Apples  Grapes  Bananas  Pear  Mangoes  Jackfruit  Strawberry  Oranges
A     102      50      100   200      700        200         400      470
B     500     150      200   300      800        300         500      570
C     250      90      140   240      740        240         440      510
D      75      45       95   195      695        195         395      465

In [ ]:
df1 10 millions # Population -> (Superset of all the Samples)

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

* head()

In [ ]:
df1.head() # Sample (Subset of Population)

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0

* tail()

In [ ]:
df1.tail()

     Name     OS  DBMS
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

In [ ]:
df1.head(2)

    Name    OS  DBMS
1  Rahul  25.0  20.0
2  Rohit  75.5  80.0

In [ ]:
df1.tail()

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

* dtypes

In [ ]:
df1.dtypes

Name     object
OS      float64
DBMS    float64
dtype: object

* empty

In [ ]:
df1.empty

False

* ndim

In [ ]:
df1.ndim

2

* shape

In [ ]:
df1.shape

(6, 3)

* size

In [ ]:
df1.size

18

* values

In [ ]:
df1.keys

<bound method NDFrame.keys of      Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0>

* describe

In [ ]:
df1.describe()

               OS       DBMS
count    6.000000   6.000000
mean    74.000000  59.500000
std     27.035162  31.979681
min     25.000000  20.000000
25%     69.125000  32.250000
50%     78.000000  67.500000
75%     92.125000  78.750000
max    100.000000  99.000000

* T

In [ ]:
df1.T

          1      2       3      4       5      7
Name  Rahul  Rohit  Venkat  Steve  Ankita  Venom
OS       25   75.5      96     67     100   80.5
DBMS     20     80      60     23      99     75

In [ ]:
df1.iloc[1]

Name    Rohit
OS       75.5
DBMS       80
Name: 2, dtype: object

In [ ]:
df1

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

In [ ]:
asd = df1.T

In [ ]:
asd.iloc[1]

1      25
2    75.5
3      96
4      67
5     100
7    80.5
Name: OS, dtype: object

* sum()

In [ ]:
df1.sum()

Name    RahulRohitVenkatSteveAnkitaVenom
OS                                   444
DBMS                                 357
dtype: object

In [ ]:
df1["OS"].sum()

444.0

In [ ]:
df1.sum(1) # 1 -> axis

1     45.0
2    155.5
3    156.0
4     90.0
5    199.0
7    155.5
dtype: float64

* mean()

In [ ]:
df1.mean()

OS      74.0
DBMS    59.5
dtype: float64

In [ ]:
df1.mean(1)

1    22.50
2    77.75
3    78.00
4    45.00
5    99.50
7    77.75
dtype: float64

In [ ]:
df1

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

* median()

In [ ]:
df1.median()

OS      78.0
DBMS    67.5
dtype: float64

In [ ]:
df1.median(1)

1    22.50
2    77.75
3    78.00
4    45.00
5    99.50
7    77.75
dtype: float64

In [ ]:
2+2

4

In [ ]:
2*2

4

* mode()

In [ ]:
df1

     Name     OS  DBMS
1   Rahul   25.0  20.0
2   Rohit   75.5  80.0
3  Venkat   96.0  60.0
4   Steve   67.0  23.0
5  Ankita  100.0  99.0
7   Venom   80.5  75.0

In [ ]:
df1.mode()

     Name     OS  DBMS
0  Ankita   25.0  20.0
1   Rahul   67.0  23.0
2   Rohit   75.5  60.0
3   Steve   80.5  75.0
4  Venkat   96.0  80.0
5   Venom  100.0  99.0

In [ ]:
df1.mode(1)

/usr/local/lib/python3.7/dist-packages/pandas/core/algorithms.py:921: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'float'
  warn(f"Unable to sort modes: {err}")
/usr/local/lib/python3.7/dist-packages/pandas/core/algorithms.py:921: UserWarning: Unable to sort modes: '<' not supported between instances of 'float' and 'str'
  warn(f"Unable to sort modes: {err}")

       0       1      2
1     20      25  Rahul
2     80   Rohit   75.5
3     96  Venkat     60
4  Steve      23     67
5    100  Ankita     99
7   80.5   Venom     75

* std

In [ ]:
df1.std()

OS      27.035162
DBMS    31.979681
dtype: float64

In [ ]:
df1.std(1)

1     3.535534
2     3.181981
3    25.455844
4    31.112698
5     0.707107
7     3.889087
dtype: float64

* min() & max()

In [ ]:
df1.min()

Name    Ankita
OS          25
DBMS        20
dtype: object

In [ ]:
df1.max()

Name    Venom
OS        100
DBMS       99
dtype: object

In [ ]:
df1.min(1)

1    20.0
2    75.5
3    60.0
4    23.0
5    99.0
7    75.0
dtype: float64

In [ ]:
df1.max(1)

1     25.0
2     80.0
3     96.0
4     67.0
5    100.0
7     80.5
dtype: float64

In [ ]:
cumsum()
cumprod()